name: List Workspace with Legacy CLI

on:
  workflow_dispatch:

jobs:
  list-workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Legacy Databricks CLI
        run: pip install databricks-cli==0.17.7

      - name: Configure CLI using secrets
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: List Workspace
        run: databricks workspace list /
