name: Databricks Workspace List (New CLI)

on:
  workflow_dispatch:

jobs:
  list-workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Install new Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash

      - name: List workspace contents
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
        run: |
          databricks workspace list /
