name: List Workspace with New CLI

on:
  workflow_dispatch:

jobs:
  list-workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Install new Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash

      - name: Authenticate and list workspace
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        run: |
          databricks config profile set github-actions --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN
          databricks workspace list / --profile github-actions
