name: Export Workspace to Feature Branch

on:
  push:
    branches:
      - main

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required to switch branches

      - name: Install Databricks CLI (new)
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash

      - name: Export Workspace Content
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          mkdir -p exported_notebooks
          databricks workspace export-dir /Workspace/Users/bijumathewt@gmail.com/Databricks exported_notebooks --overwrite

      - name: Switch to feature1 branch
        run: |
          git checkout feature1 || git checkout -b feature1

      - name: Copy exported notebooks to tracked folder
        run: |
          mkdir -p workspace_backup
          cp -r exported_notebooks/* workspace_backup/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add workspace_backup
          git commit -m "🚀 Exported notebooks from workspace" || echo "No changes to commit"
          git push origin feature1
