name: Copy Note Books

on:
  workflow_dispatch

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy to Dev Workspace
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI v0.205+
        run: |
          pip install databricks-cli

      - name: Create Databricks profile from secrets
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          mkdir -p ~/.databricks
          databricks auth login --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN --profile github-actions-profile

      - name: List workspace root
        run: databricks workspace list / --profile github-actions-profile
