name: Copy Note Books

on:
  workflow_dispatch

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy to Dev Workspace
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI v0.205+
        run: |
          pip install databricks-cli[bundle] --upgrade

      - name: Configure Databricks CLI for Dev
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databricks/config
          {
            "default": {
              "host": "${{ secrets.DATABRICKS_HOST_DEV }}",
              "token": "${{ secrets.DATABRICKS_TOKEN_DEV }}"
            }
          }
      - name: Export notebooks from source folder
        run: |
           databricks workspace list / --profile DEFAULT

