name: Deploy to Test Workspace

on:
  workflow_dispatch:

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Databricks CLI v0.200+
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
      - name: Login to Dev
        env:
          DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN_DEV }}
          DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST_DEV }}
        run: |
          databricks auth login --host $DATABRICKS_HOST_DEV --token $DATABRICKS_TOKEN_DEV --profile dev-env
      - name: Authenticate with Databricks
        env:
          DATABRICKS_TOKEN: ${{ secrets.TEST_DATABRICKS_TOKEN_DEV }}
          DATABRICKS_HOST: ${{ secrets.TEST_DATABRICKS_HOST_DEV }}
        run: |
          databricks auth login --host $DATABRICKS_HOST_DEV --token $DATABRICKS_TOKEN_DEV --profile test-env

      - name: Deploy Bundle to Test
        run: |
          databricks bundle deploy --target test --profile test-env
