name: Deploy to Test Workspace

on:
  workflow_dispatch:

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash

      - name: Authenticate with Dev Databricks
        run: |
          databricks configure profile set dev-env --host $DATABRICKS_HOST_DEV --token $DATABRICKS_TOKEN_DEV
        env:
          DATABRICKS_HOST_DEV: ${{ secrets.DEV_DATABRICKS_HOST }}
          DATABRICKS_TOKEN_DEV: ${{ secrets.DEV_DATABRICKS_TOKEN }}

      - name: Authenticate with Test Databricks
        run: |
          databricks configure profile set test-env --host $DATABRICKS_HOST_TEST --token $DATABRICKS_TOKEN_TEST
        env:
          DATABRICKS_HOST_TEST: ${{ secrets.TEST_DATABRICKS_HOST }}
          DATABRICKS_TOKEN_TEST: ${{ secrets.TEST_DATABRICKS_TOKEN }}

      - name: Validate Bundle (Optional)
        run: |
          databricks bundle validate --target dev --profile dev-env

      - name: Deploy Bundle to Test
        run: |
          databricks bundle deploy --target test --profile test-env
